export const biscuits = [
  {
    id: 1,
    biscuit_name: "bourbon",
    src: "https://images.unsplash.com/photo-1603194556500-bdd4c947a952?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Chocolate biscuit with goldilocks dunkability",
    crunchiness: 6,
    dunkability: 10,
    flavour: "chocolate",
    colour: "brown",
    packet_amount: 20,
  },
  {
    id: 2,
    biscuit_name: "custard cream",
    src: "https://thegreatbritishbakeoff.co.uk/wp-content/uploads/2023/10/prue-custard-creams-square.jpg",
    description: "Creamy biscuit",
    crunchiness: 5,
    dunkability: 8,
    flavour: "vanilla",
    colour: "beige",
    packet_amount: 24,
  },

  {
    id: 3,
    biscuit_name: "hobnob",
    src: "https://upload.wikimedia.org/wikipedia/commons/9/95/Hobnobs.jpg",
    description: "Oaty biscuits",
    crunchiness: 6,
    dunkability: 7,
    flavour: "oat",
    colour: "almond",
    packet_amount: 12,
  },
  {
    id: 4,
    biscuit_name: "Chocolate Cookies",
    src: "https://images.unsplash.com/photo-1589988802149-7f9cb13a468e?q=80&w=1941&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Chocolate biscuits",
    crunchiness: 6,
    dunkability: 7,
    flavour: "Chocolate",
    colour: "brown",
    packet_amount: 12,
  },
  {
    id: 5,
    biscuit_name: "Ginger Nuts",
    src: "https://images.unsplash.com/photo-1557089706-68d02dbda277?q=80&w=2076&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Mouth-watering piece of heaven",
    crunchiness: 6,
    dunkability: 7,
    flavour: "ginger",
    colour: "almond",
    packet_amount: 12,
  },
];

export let manufacturer = {
  manufacturer_name: "Joe",
  budget: 300000,
};
